# GitHub Actions
name: Auto CheckIn

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  CheckIn:
    name: Auto Run
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set Timezone to UTC+8
        run: |
          sudo timedatectl set-timezone Asia/Taipei
          echo "Current time: $(date)"

      - name: Setting Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        env:
          HoyolabData: ${{ secrets.HOYOLAB_COOKIE }}
          DiscordData: ${{ secrets.DISCORD_COOKIE }}
          LevelinfiniteData: ${{ secrets.LEVELINFINITE_COOKIE }}
        run: |
          python Main.py

      - name: Commit Log
        run: |
          git config --global user.name 'Canaan-HS'
          git config --global user.email 's3459897@gmail.com'

          if [[ -n $(git status -s) ]]; then
            git add -A
            git commit -m "Run log"
            git push
          else
            echo "No changes to commit"
          fi
